CREATE WAREHOUSE CRICKET_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- ============================================================
-- CRICKET ANALYTICS PROJECT
-- DATABASE & SCHEMA SETUP
-- ============================================================

-- Create project database
CREATE DATABASE CRICKET_ANALYTICS;

-- Explicitly switch to the project database
USE DATABASE CRICKET_ANALYTICS;

-- Create project schemas
CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;
CREATE SCHEMA DW;


-- ============================================================
-- DEFAULT POWERPLAY CONFIGURATION
-- Some JSON files may not contain powerplay information
-- ============================================================

CREATE OR REPLACE TABLE CRICKET_ANALYTICS.RAW.DEFAULT_POWERPLAYS
(
    MATCH_TYPE VARCHAR(10),
    START_OVER INT,
    END_OVER INT
);

INSERT INTO CRICKET_ANALYTICS.RAW.DEFAULT_POWERPLAYS
VALUES
    ('ODI', 1, 10),
    ('T20', 1, 6);


-- ============================================================
-- RAW DATA
-- This table will receive the JSON files from Snowpipe
-- ============================================================

CREATE OR REPLACE TABLE CRICKET_ANALYTICS.RAW.RAW_DATA
(
    RAW_FILE VARIANT,
    FILENAME VARCHAR(100)
);


-- ============================================================
-- STAGING RAW DATA
-- Holds incremental data read from the RAW stream
-- ============================================================

CREATE OR REPLACE TABLE CRICKET_ANALYTICS.STAGING.STG_RAW_DATA
LIKE CRICKET_ANALYTICS.RAW.RAW_DATA;


-- ============================================================
-- STAGING TABLES
-- ============================================================

CREATE OR REPLACE TABLE CRICKET_ANALYTICS.STAGING.STG_MATCH_INFO
(
    MATCH_TYPE VARCHAR(200),
    GENDER VARCHAR(200),
    SEASON VARCHAR(200),
    CITY VARCHAR(200),
    VENUE VARCHAR(200),
    MATCH_DATE DATE,
    TEAM1 VARCHAR(200),
    TEAM2 VARCHAR(200),
    TOSS_WINNER VARCHAR(200),
    TOSS_DECISION VARCHAR(200),
    MATCH_WINNER VARCHAR(200),
    MARGIN VARCHAR(200),
    EVENT_NAME VARCHAR(200),
    EVENT_TYPE VARCHAR(200),
    POM VARCHAR(200),
    FILENAME VARCHAR(100)
);


CREATE OR REPLACE TABLE CRICKET_ANALYTICS.STAGING.STG_MATCH_INNINGS
(
    INNING_ID NUMBER(38,0),
    OVER NUMBER(38,0),
    BATTING_TEAM VARCHAR(200),
    BALL_IN_OVER NUMBER(38,0),
    BATTER VARCHAR(200),
    BOWLER VARCHAR(200),
    NON_STRIKER VARCHAR(200),
    RUNS_BATTER NUMBER(38,0),
    EXTRA_TYPE VARCHAR(200),
    RUNS_EXTRAS NUMBER(38,0),
    RUNS_TOTAL NUMBER(38,0),
    DISMISSAL_KIND VARCHAR(200),
    OUT_PLAYER VARCHAR(200),
    POWERPLAYS_START_OVER FLOAT,
    POWERPLAYS_END_OVER FLOAT,
    IS_POWERPLAY NUMBER(1,0),
    FILENAME VARCHAR(100)
);


CREATE OR REPLACE TABLE CRICKET_ANALYTICS.STAGING.STG_PLAYERS
(
    PLAYER_NAME VARCHAR(200),
    TEAM_NAME VARCHAR(200)
);


CREATE OR REPLACE TABLE CRICKET_ANALYTICS.STAGING.STG_TEAMS
(
    TEAM_NAME VARCHAR(200),
    TEAM_TYPE VARCHAR(200)
);


-- ============================================================
-- DATA WAREHOUSE TABLES
-- ============================================================

CREATE OR REPLACE TABLE CRICKET_ANALYTICS.DW.MATCH_INFO
(
    MATCH_ID NUMBER(19,0),
    MATCH_TYPE VARCHAR(200),
    GENDER VARCHAR(200),
    SEASON VARCHAR(200),
    CITY VARCHAR(200),
    VENUE VARCHAR(200),
    MATCH_DATE DATE,
    TEAM1_ID NUMBER(19,0),
    TEAM2_ID NUMBER(19,0),
    TOSS_WINNER_ID NUMBER(19,0),
    TOSS_DECISION VARCHAR(200),
    MATCH_WINNER_ID NUMBER(19,0),
    MARGIN VARCHAR(200),
    EVENT_NAME VARCHAR(200),
    EVENT_TYPE VARCHAR(200),
    POM_ID NUMBER(19,0),
    FILENAME VARCHAR(100)
);


CREATE OR REPLACE TABLE CRICKET_ANALYTICS.DW.MATCH_INNINGS
(
    MATCH_ID NUMBER(19,0),
    INNING_ID NUMBER(38,0),
    OVER NUMBER(38,0),
    BATTING_TEAM VARCHAR(200),
    BALL_IN_OVER NUMBER(38,0),
    BATTER VARCHAR(200),
    BOWLER VARCHAR(200),
    NON_STRIKER VARCHAR(200),
    RUNS_BATTER NUMBER(38,0),
    EXTRA_TYPE VARCHAR(200),
    RUNS_EXTRAS NUMBER(38,0),
    RUNS_TOTAL NUMBER(38,0),
    DISMISSAL_KIND VARCHAR(200),
    OUT_PLAYER VARCHAR(200),
    IS_POWERPLAY NUMBER(1,0)
);


CREATE OR REPLACE TABLE CRICKET_ANALYTICS.DW.PLAYERS
(
    PLAYER_ID NUMBER(38,0),
    PLAYER_NAME VARCHAR(100),
    TEAMS ARRAY
);


CREATE OR REPLACE TABLE CRICKET_ANALYTICS.DW.TEAMS
(
    TEAM_ID NUMBER(19,0),
    TEAM_NAME VARCHAR(200),
    TEAM_TYPE VARCHAR(200)
);


-- ============================================================
-- SEQUENCES
-- ============================================================

CREATE OR REPLACE SEQUENCE CRICKET_ANALYTICS.RAW.SEQ_TEAMS;

CREATE OR REPLACE SEQUENCE CRICKET_ANALYTICS.RAW.SEQ_PLAYERS;

CREATE OR REPLACE SEQUENCE CRICKET_ANALYTICS.RAW.SEQ_MATCHES;